language: swift
osx_image: xcode9.4
xcode_project: Youse-Auto.xcworkspace
xcode_scheme: Youse-Auto
xcode_sdk: iphonesimulator11.4

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/wascar-*/
- rvm use $RVM_RUBY_VERSION
- brew update
- brew install swiftlint
- pod repo update

script:
- xcodebuild -workspace Youse-Auto.xcworkspace -scheme Youse-Auto -destination "platform=iOS Simulator,name=iPhone X,OS=11.4" clean test | xcpretty