disabled_rules: # rule identifiers to exclude from running
  - trailing_newline
  - trailing_whitespace
  - variable_name
  - missing_docs
  - type_name
  - force_cast
  - vertical_parameter_alignment
  - empty_parentheses_with_trailing_clousure
  - empty_enum_arguments
  - line_length
opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules
#included: # paths to include during linting. `--path` is ignored if present.
  #- Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
# rules that have both warning and error levels, can set just the warning level
# implicitly
# they can set both implicitly with an array
type_body_length:
  warning: 600
  error: 2000
# or they can set both explicitly
file_length:
  warning: 600
  error: 1200
function_body_length:
  warning: 70
  error: 100
cyclomatic_complexity:
  warning: 25
  error: 40
function_parameter_count:
  warning: 7
  error: 12
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
